version: "3.8"

services:
  broker01:
    image: confluentinc/cp-kafka:latest #apache/kafka:latest
    container_name: broker01
    healthcheck:
      test: nc -z broker01 9093 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    ports:
      - "9094:9094"
    environment:
      CLUSTER_ID: "kafka-cluster"
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: SASL_PLAINTEXT://broker01:9093,LOCAL://:9094,CONTROLLER://broker01:9095
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://broker01:9093,LOCAL://broker01:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,LOCAL:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker01:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN, SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: "User:admin;User:controller"

      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="controller" password="controller" user_controller="controller";
      KAFKA_CONTROLLER_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
    volumes:
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  broker02:
    image: confluentinc/cp-kafka:latest #apache/kafka:latest
    container_name: broker02
    healthcheck:
      test: nc -z broker02 9096 || exit -1
      interval: 5s
      timeout: 10s
      retries: 10
      start_period: 15s
    ports:
      - "9096:9096"
    environment:
      CLUSTER_ID: "kafka-cluster"
      KAFKA_NODE_ID: 2
      KAFKA_PROCESS_ROLES: broker
      KAFKA_LISTENERS: SASL_PLAINTEXT://broker02:9096,LOCAL://:9094
      KAFKA_ADVERTISED_LISTENERS: SASL_PLAINTEXT://broker02:9096,LOCAL://broker02:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: SASL_PLAINTEXT

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:SASL_PLAINTEXT,LOCAL:SASL_PLAINTEXT,SASL_PLAINTEXT:SASL_PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER

      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker01:9095
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_SASL_ENABLED_MECHANISMS: PLAIN, SCRAM-SHA-256
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: PLAIN
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf"

      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: false
      KAFKA_SUPER_USERS: "User:admin;User:controller"

      KAFKA_LISTENER_NAME_CONTROLLER_SASL_ENABLED_MECHANISMS: PLAIN
      KAFKA_LISTENER_NAME_CONTROLLER_PLAIN_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="controller" password="controller" user_controller="controller";
      KAFKA_CONTROLLER_ENABLED_MECHANISMS: PLAIN
      KAFKA_SASL_MECHANISM_CONTROLLER_PROTOCOL: PLAIN
    volumes:
      - ./kafka_server_jaas.conf:/etc/kafka/kafka_server_jaas.conf

  kafka-web-ui:
    image: provectuslabs/kafka-ui
    container_name: kafkaweb-ui
    restart: "no"
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: "true"
    volumes:
      - ./kui.yml:/etc/kafkaui/dynamic_config.yaml
    depends_on:
      - "broker01"

  connect:
    image: confluentinc/cp-kafka-connect:latest
    container_name: connect
    hostname: connect
    depends_on:
      - broker01
    ports:
      - 8083:8083
    environment:
      CONNECT_BOOTSTRAP_SERVERS: "broker01:9093"
      CONNECT_REST_PORT: "8083"
      CONNECT_GROUP_ID: "local-connect"
      CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR: "-1" # use broker settings
      CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR: "-1" # use broker settings
      CONNECT_STATUS_STORAGE_REPLICATION_FACTOR: "-1" # use broker settings
      CONNECT_CONFIG_STORAGE_TOPIC: "local-connect-config"
      CONNECT_OFFSET_STORAGE_TOPIC: "local-connect-offsets"
      CONNECT_STATUS_STORAGE_TOPIC: "local-connect-status"
      CONNECT_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_ADVERTISED_HOST_NAME: "connect"
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CONNECT_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_SASL_MECHANISM: PLAIN
      CONNECT_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin" password="admin-secret";
      CONNECT_PRODUCER_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_PRODUCER_SASL_MECHANISM: PLAIN
      CONNECT_PRODUCER_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin" password="admin-secret";
      CONNECT_CONSUMER_SECURITY_PROTOCOL: SASL_PLAINTEXT
      CONNECT_CONSUMER_SASL_MECHANISM: PLAIN
      CONNECT_CONSUMER_SASL_JAAS_CONFIG:
        org.apache.kafka.common.security.plain.PlainLoginModule required
        username="admin" password="admin-secret";
      CONNECT_PLUGIN_PATH: /usr/share/java/,/etc/kafka-connect/jars
    volumes:
      - ./connect:/etc/kafka-connect/jars

  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres/custom-config.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c config_file=/etc/postgresql/postgresql.conf

  init-kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - connect
    volumes:
      - ./scripts/:/scripts
      - ./admin.properties:/etc/kafka/admin.properties
    entrypoint: ["/bin/bash", "-c", "/scripts/init.sh"]

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      init-kafka:
        condition: service_completed_successfully
      broker01:
        condition: service_healthy

  nifi:
    image: apache/nifi:1.19.1
    container_name: nifi01
    ports:
      - "8443:8443"
    ulimits:
      nofile:
        soft: 4096
        hard: 8192
    environment:
      - SINGLE_USER_CREDENTIALS_USERNAME=admin
      - SINGLE_USER_CREDENTIALS_PASSWORD=ctsBtRBKHRAx69EqUghvvgEvjnaLjFEB
      - NIFI_WEB_PROXY_HOST=nifi01,localhost
      - NIFI_WEB_HTTPS_HOST=nifi01
      - NIFI_SENSITIVE_PROPS_KEY=p+FZ7aIZmaWAXmqbw8qwyawJiC714V5R
    volumes:
      - ./nifi/:/opt/nifi/nifi-current/conf/
